#!/bin/bash

cpu=`top -bn1 | 
	grep "Cpu(s)" | 
	sed "s/.*, *\([0-9.]*\)%* id.*/\1/" |
	awk '{print 100 - $1}'`

echo -e " $cpu%"


case $BLOCK_BUTTON in
	  1) st -e htop ;;
    3) notify-send "CPU usage" "$(ps axch -o cmd,%cpu --sort=-%cpu | head)" ;;
	  2) st -e nvim "$0" ;;
esac
