#!/bin/bash


choices="Terminal                 (super+shift+enter)
lf                                 (super+r)
Firefox                            (super+f)
vs-code                            (super+v)
neovim                             (super+n)\n"

chosen=$(echo -e "${choices[@]::-2}" | dmenu -fn "JetBrainsMono Nerd Font:size=12" -l "20" -p " ")

chosen=${chosen%% *} # ignore keybind ( only take first word )

case "$chosen" in
        Terminal) st ;;
        lf) st -e zsh -ic "lfcd; zsh" ;;
        Firefox) firefox ;;
        vs-code) vscodium ;;
        neovim) st -e zsh -ic "nvim; zsh" 
esac
