#!/bin/sh

files=$( ls -p ~/Pictures/wallpaper/ | grep -v /)

choices="RANDOM\nBROWSE"

# read files into string
echo "$files" | tr ' ' '\n' | (while read i
do
    choices="$choices""\n"
    choices="$choices""$i"
done

chosen=$(printf ${choices} | dmenu -fn "JetBrainsMono Nerd Font:size=12" -l "20" -p "󰸉 ")

case "$chosen" in
        RANDOM) # random wallpaper
          file=$(ls -p ~/Pictures/wallpaper/ | grep -v / | shuf -n 1);
          # xprop command forces a dwm refresh
          xwallpaper --zoom ~/Pictures/wallpaper/$file && xprop -root -remove _NET_ACTIVE_WINDOW ;;
        BROWSE) # browse wallpapers in sxiv
            xwallpaper --zoom $(sxiv -ot ~/Pictures/wallpaper/* | head -n 1);;
        *)      # if a specific wallpaper is chosen
          xwallpaper --zoom ~/Pictures/wallpaper/$chosen ;;
esac

)
