[manager]
prepend_keymap = [
    { on = "<Backspace>", run = "hidden toggle", desc = "Toggle the visibility of hidden files" },
	{ on = "l",           run = "plugin smart-enter",         desc = "Open selected files" },
]
